# Generated by Django 5.2.5 on 2025-08-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndiceMassaCorporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(default=0.0, verbose_name='peso')),
                ('altura', models.FloatField(default=0.0, verbose_name='altura')),
            ],
        ),
    ]
