# Generated by Django 5.2.5 on 2025-08-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiceMassaCorporal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicemassacorporal',
            name='resultado_imc',
            field=models.FloatField(default=0.0, verbose_name='resultado'),
        ),
    ]
