# Generated by Django 5.2.5 on 2025-08-17 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indiceMassaCorporal', '0002_indicemassacorporal_resultado_imc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndiceMassaCorporal',
        ),
    ]
