# Generated by Django 5.2.5 on 2025-08-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indiceMassaCorporal', '0003_delete_indicemassacorporal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcularIMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(verbose_name='peso')),
                ('altura', models.FloatField(verbose_name='altura')),
            ],
        ),
    ]
